### ISSUE TITLE
Unable to build sysadm on freebsd 10.3 or 11

### ISSUE THREAD

**Issue by telefax** [trueos/sysadm-docs#1]
I tried to find a way to contact you for issues, but cannot find any, so I'll try here since I tried to follow the installation guide on https://sysadm.us/handbook/server/basics.html#building-sysadm
on Freebsd 10.3 release as well on Freebsd 11 Release. 

Both bails out on qmake, this is from freebsd 10.3:

> /usr/local/lib/qt5/bin/qmake -recursive
> /usr/local/lib/qt5/bin/qmake: Command not found.

Is this supposed to run on FreeBSD?
on www.sysadm.us you can read

> SysAdm™ is a FreeBSD-based service which provides a stable API for administrating FreeBSD and TrueOS systems.

I'm a little bit confused, so much basic information is missing on the web page and in the documentation, also there is no issue tracker except for the documentation here?

Thanks

**Comment by Mrt134** [comment]
We are in the middle of consolidating our issues trackers amongst the TrueOS/Lumina repos, sorry about the confusion. All new issues (except for docs) are now supposed to be filed in the [trueos-core issue tracker](https://github.com/trueos/trueos-core/issues). I'll duplicate this issue in that repo so the appropriate person can look at it.

**Comment by beanpole135** [comment]
@telefax 
You need Qt5 installed on the system before you can use it to build SysAdm - that is one of the base dependencies.
Just run `pkg install qt5` to install the whole set of Qt5 packages (build tools, modules, etc) and then retry it.

**Comment by telefax** [comment]
Thank you, that definately made a difference :)
Compilation now went without a hitch, but make install gives me this

> 
> root@sysadm:~/dl/sysadm/src # make install
> cd server/ && ( test -e Makefile || /usr/local/lib/qt5/bin/qmake /root/dl/sysadm/src/server/server.pro -o Makefile ) && make -f Makefile install
> install -m 755 -p sysadm-binary /usr/local/bin/sysadm-binary
> strip /usr/local/bin/sysadm-binary
> install sysadm-server /usr/local/bin/
> cd bridge/ && ( test -e Makefile || /usr/local/lib/qt5/bin/qmake /root/dl/sysadm/src/bridge/bridge.pro -o Makefile ) && make -f Makefile install
> install -m 755 -p sysadm-bridge /usr/local/bin/sysadm-bridge
> strip /usr/local/bin/sysadm-bridge
> install sysadm-bridge-start /usr/local/bin/
> install -m 755 -p /root/dl/sysadm/src/rc.d/sysadm /usr/local/etc/rc.d/
> strip /usr/local/etc/rc.d/sysadm
> strip: /usr/local/etc/rc.d/sysadm: File format not recognized
> *** Error code 1 (ignored)
> install -m 755 -p /root/dl/sysadm/src/rc.d/sysadm-rest /usr/local/etc/rc.d/
> strip /usr/local/etc/rc.d/sysadm-rest
> strip: /usr/local/etc/rc.d/sysadm-rest: File format not recognized
> *** Error code 1 (ignored)
> install -m 755 -p /root/dl/sysadm/src/rc.d/sysadm-bridge /usr/local/etc/rc.d/
> strip /usr/local/etc/rc.d/sysadm-bridge
> strip: /usr/local/etc/rc.d/sysadm-bridge: File format not recognized
> *** Error code 1 (ignored)
> install -m 755 -p /root/dl/sysadm/src/init.d/sysadm /usr/local/etc/init.d/
> strip /usr/local/etc/init.d/sysadm
> strip: /usr/local/etc/init.d/sysadm: File format not recognized
> *** Error code 1 (ignored)
> install -m 755 -p /root/dl/sysadm/src/init.d/sysadm-rest /usr/local/etc/init.d/
> strip /usr/local/etc/init.d/sysadm-rest
> strip: /usr/local/etc/init.d/sysadm-rest: File format not recognized
> *** Error code 1 (ignored)
> install -m 755 -p /root/dl/sysadm/src/init.d/sysadm-bridge /usr/local/etc/init.d/
> strip /usr/local/etc/init.d/sysadm-bridge
> strip: /usr/local/etc/init.d/sysadm-bridge: File format not recognized
> *** Error code 1 (ignored)
> cp conf/sysadm.conf /usr/local/etc/sysadm.conf.dist

Not sure why tries to do strip on ascii files, but it works anyway.
Maybe this is material for another ticket, along with the rest of the documentation quirks :p

**Comment by beanpole135** [comment]
That is just one of the quirks about qmake - those "strip" errors are just ignored/warnings because qmake does not understand that not every installed file is a binary - those ones in particular are just text files.

**Comment by Mrt134** [comment]
I'm going to go ahead and close this issue now. Feel free to open more docs issues in this or the other docs trackers. I've also added a "general info" section to most TrueOS project readmes. These hopefully clear up where to file issues and the general lack of basic info in some of the repositories. Thanks!
