### ISSUE TITLE
sysadm.us certificate issue

### ISSUE THREAD

**Issue by Deb2BSD** [trueos/sysadm-docs#24]

**Comment by Deb2BSD** [comment]
firefox opera and waterfox all refuse to connect to
sysadm.us saying the certificate is not correct, with
variations of the following message:
Your connection is not secure
The owner of sysadm.us has configured their website
improperly. To protect your information from being
stolen, Waterfox has not connected to this website.

All efforts to obtain handbooks/tutorials fail as I cannot open the page.

**Comment by JoshDW19** [comment]
You caught us right as we were pulling the site down :). TrueOS doesn't use sysadm any longer so we've discontinued the site.

**Comment by beanpole135** [comment]
Just to clarify Josh's comment.
**Only** the website for SysAdm is getting disabled, not the utility itself.
The SysAdm tools are still being developed and used by TrueOS, but it is just being treated more as a backend utility/framework and does not need it's own dedicated/promotional website.
